### ISSUE TITLE
Support Jackson 2.10.0

### ISSUE THREAD

**Issue by johanhaleby** [openapi-tools/jackson-dataformat-hal#21]
I've upgraded to Spring Boot 2.2.0 which uses Jackson 2.10.0 but when I do so I get an error when the HAL resources are serialized:

```java
Caused by: java.lang.IllegalStateException: null
	at com.fasterxml.jackson.databind.ser.std.NumberSerializer$BigDecimalAsStringSerializer.valueToString(NumberSerializer.java:161)
	at com.fasterxml.jackson.databind.ser.std.NumberSerializer$BigDecimalAsStringSerializer.isEmpty(NumberSerializer.java:132)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:711)
	at io.openapitools.jackson.dataformat.hal.ser.HALBeanSerializer$FilteredProperties.serialize(HALBeanSerializer.java:191)
```

I suspect that there's some change in Jackson 2.10 which makes `jackson-dataformat-hal` incompatible with this version.

**Comment by johanhaleby** [comment]
This was a bug in Jackson which will be fixed in 2.10.1.

**Comment by langecode** [comment]
Thx for reporting (and closing again) - glad that you find value in our library.

**Comment by johanhaleby** [comment]
@langecode Thanks a lot for your efforts on this! It has been really useful for creating HAL based API's.
